### ISSUE TITLE
Memory usage increases throughout fault injection campaign

### ISSUE THREAD

**Issue by jcmarsh** [CHREC/drseus#1]
Longer fault injection campaigns (JTAG) fail after several hundred injections with `OSError: [Errno 12] Cannot allocate memory`

I traced the issue back to the django database. The problem is that the database is configured in DEBUG mode, which means that it keeps a list of queries. The fix is to either occasionally clear this list or to turn off DEBUG mode. (https://stackoverflow.com/a/2338335/1601162)

**Comment by jcmarsh** [comment]
I don't have push access to this repo... here's the fix in mine: https://github.com/jcmarsh/drseus/commit/404b83553ad6ff7925f44b34e6a50b2910b7a177

It's just one line turning DEBUG from True to False.

**Comment by jcmarsh** [comment]
This does have some security consequences, and requires that you add `ALLOWED_HOSTS=['127.0.0.1'],` to the settings and run with `./drseus.py django runserver --insecure`

**Comment by ssroffe** [comment]
Fixed. Apologies for the delay. I haven't looked at this repo in a really long time.
